### ISSUE TITLE
Add handler to create "upvote" reaction to questions in stage channel

### ISSUE THREAD

**Issue by johndaniels** [The-Expanse-Discord/rocinante-discord#32]
We want to have the bot respond to questions in a "stage" channel  with an "upvote" reaction. Based on the number of upvotes, we can choose which questions to ask guests. 

The "stage" channel to use should be an option in the configuration file.

**Comment by kata-gatame** [comment]
this issue was resolved with 5d2d0a118c16ea47868d52826d376a95f3139e2e
